# Generated by Django 4.2.5 on 2024-02-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0003_lnmonline_amount_lnmonline_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lnmonline',
            name='cart',
        ),
    ]
